### ISSUE TITLE
tumor eQTL

### ISSUE THREAD

**Issue by xtmgah** [guigolab/sQTLseekeR#1]
Hello:

Thanks for your previously answer about the F-socre. Is there any way to used this package for Tumor sQTL analysis. For example, each gene may have different copy number change. and there are may have different somatic mutations... some may have impact on the splicing.. So, is there any way to adjust there things  or do you have any idea about this. Thanks.

**Comment by jmonlong** [comment]
By design the copy number changes should not affect or bias the sQTL analysis because it tests the relative usage of the different transcripts. No matter how the global gene expression changes, sQTLseekeR tests if the transcripts usage is associated to a variant. So no need for adjusting and I would run sQTLseekeR normally with the somatic mutations as *genotype input*. 

Note: I'm assuming that the copy number aberration affects the whole gene, as it is likely the case for large copy number aberrations. It's a different story if only part of the gene is gained/lost. The transcript quantification will be affected and the actual transcripts produced by the gene might be too. I don't know how often this happen. If you are not interested in these cases, you could try to flag these genes beforehand (if you have accurate copy number aberrations breakpoints), or you could double-check your favorite sQTLs afterwards to make sure they are really associated with the somatic mutation.

**Comment by xtmgah** [comment]
Thanks. that makes sense.
